# syntax=docker/dockerfile:1

FROM golang:1.23 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/input-service ./cmd/input-service

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /out/input-service ./input-service

EXPOSE 8081

ENTRYPOINT ["/app/input-service"]
