services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      VIACEP_BASE_URL: ${VIACEP_BASE_URL:-https://viacep.com.br/ws}
      WEATHER_API_BASE_URL: ${WEATHER_API_BASE_URL:-https://api.weatherapi.com/v1}
